// <auto-generated />
using System;
using FolketingetVotes.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FolketingetVotes.Data.Persistence.Migrations
{
    [DbContext(typeof(FolketingetDbContext))]
    [Migration("20260916125211_AddPartyIsIndependentGroup")]
    partial class AddPartyIsIndependentGroup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("BiographyPartyShortName")
                        .HasColumnType("text")
                        .HasColumnName("biography_party_short_name");

                    b.Property<string>("BiographyXml")
                        .HasColumnType("text")
                        .HasColumnName("biography_xml");

                    b.Property<DateOnly?>("Born")
                        .HasColumnType("date")
                        .HasColumnName("born");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("GroupShortName")
                        .HasColumnType("text")
                        .HasColumnName("group_short_name");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("text")
                        .HasColumnName("picture_url");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_actors_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_actors_type_id");

                    b.HasIndex("TypeId", "GroupShortName")
                        .HasDatabaseName("ix_actors_type_id_group_short_name");

                    b.ToTable("actors", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.ActorRelation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<int>("FromActorId")
                        .HasColumnType("integer")
                        .HasColumnName("from_actor_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("ToActorId")
                        .HasColumnType("integer")
                        .HasColumnName("to_actor_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_actor_relations");

                    b.HasIndex("FromActorId", "RoleId")
                        .HasDatabaseName("ix_actor_relations_from_actor_id_role_id");

                    b.HasIndex("ToActorId", "RoleId")
                        .HasDatabaseName("ix_actor_relations_to_actor_id_role_id");

                    b.ToTable("actor_relations", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Ballot", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VoteId")
                        .HasColumnType("integer")
                        .HasColumnName("vote_id");

                    b.HasKey("Id")
                        .HasName("pk_ballots");

                    b.HasIndex("VoteId")
                        .HasDatabaseName("ix_ballots_vote_id");

                    b.HasIndex("ActorId", "VoteId")
                        .HasDatabaseName("ix_ballots_actor_id_vote_id");

                    b.ToTable("ballots", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.BillSummary", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_url");

                    b.HasKey("CaseId")
                        .HasName("pk_bill_summaries");

                    b.ToTable("bill_summaries", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.BiographyMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Constituency")
                        .HasColumnType("text")
                        .HasColumnName("constituency");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_temporary");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_name");

                    b.Property<string>("PartyShortName")
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_biography_memberships");

                    b.HasIndex("PersonId", "StartDate")
                        .HasDatabaseName("ix_biography_memberships_person_id_start_date");

                    b.ToTable("biography_memberships", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.CaseActor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_actors");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_actors_case_id");

                    b.HasIndex("ActorId", "RoleId")
                        .HasDatabaseName("ix_case_actors_actor_id_role_id");

                    b.ToTable("case_actors", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.CaseKeyword", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<int>("KeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_keywords");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_keywords_case_id");

                    b.HasIndex("KeywordId")
                        .HasDatabaseName("ix_case_keywords_keyword_id");

                    b.ToTable("case_keywords", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.CaseStep", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("FolketingstidendeUrl")
                        .HasColumnType("text")
                        .HasColumnName("folketingstidende_url");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_case_steps");

                    b.HasIndex("CaseId")
                        .HasDatabaseName("ix_case_steps_case_id");

                    b.ToTable("case_steps", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Keyword", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_keywords");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_keywords_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("keywords", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Lookup", b =>
                {
                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Kind", "Id")
                        .HasName("pk_lookups");

                    b.ToTable("lookups", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<string>("Room")
                        .HasColumnType("text")
                        .HasColumnName("room");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_meetings");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_meetings_date");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_meetings_period_id");

                    b.ToTable("meetings", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.ParliamentaryCase", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<bool>("IsBudgetCase")
                        .HasColumnType("boolean")
                        .HasColumnName("is_budget_case");

                    b.Property<DateTime?>("LawDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("law_date");

                    b.Property<int?>("LawNumber")
                        .HasColumnType("integer")
                        .HasColumnName("law_number");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<int?>("NumberNumeric")
                        .HasColumnType("integer")
                        .HasColumnName("number_numeric");

                    b.Property<string>("NumberPostfix")
                        .HasColumnType("text")
                        .HasColumnName("number_postfix");

                    b.Property<string>("NumberPrefix")
                        .HasColumnType("text")
                        .HasColumnName("number_prefix");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<string>("RetsinformationUrl")
                        .HasColumnType("text")
                        .HasColumnName("retsinformation_url");

                    b.Property<string>("ShortTitle")
                        .HasColumnType("text")
                        .HasColumnName("short_title");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VotingConclusion")
                        .HasColumnType("text")
                        .HasColumnName("voting_conclusion");

                    b.HasKey("Id")
                        .HasName("pk_cases");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("ix_cases_period_id");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_cases_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("TypeId", "PeriodId")
                        .HasDatabaseName("ix_cases_type_id_period_id");

                    b.ToTable("cases", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Party", b =>
                {
                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<DateOnly?>("FirstSeen")
                        .HasColumnType("date")
                        .HasColumnName("first_seen");

                    b.Property<bool>("IsIndependentGroup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_independent_group");

                    b.Property<DateOnly?>("LastSeen")
                        .HasColumnType("date")
                        .HasColumnName("last_seen");

                    b.Property<int?>("LatestGroupActorId")
                        .HasColumnType("integer")
                        .HasColumnName("latest_group_actor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("ShortName")
                        .HasName("pk_parties");

                    b.ToTable("parties", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.PartyAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("party_name");

                    b.Property<string>("PartyShortName")
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<string>("SourceFile")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source_file");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_party_accounts");

                    b.HasIndex("Year", "PartyName")
                        .IsUnique()
                        .HasDatabaseName("ix_party_accounts_year_party_name");

                    b.ToTable("party_accounts", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.PartyDonation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("currency");

                    b.Property<string>("DonorAddress")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("donor_address");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("donor_name");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("PartyAccountId")
                        .HasColumnType("integer")
                        .HasColumnName("party_account_id");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer")
                        .HasColumnName("source_page");

                    b.HasKey("Id")
                        .HasName("pk_party_donations");

                    b.HasIndex("DonorName")
                        .HasDatabaseName("ix_party_donations_donor_name");

                    b.HasIndex("PartyAccountId")
                        .HasDatabaseName("ix_party_donations_party_account_id");

                    b.ToTable("party_donations", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.PartyMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("GroupActorId")
                        .HasColumnType("integer")
                        .HasColumnName("group_actor_id");

                    b.Property<string>("PartyShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<int?>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_party_memberships");

                    b.HasIndex("PartyShortName", "PeriodId")
                        .HasDatabaseName("ix_party_memberships_party_short_name_period_id");

                    b.HasIndex("PersonId", "StartDate")
                        .HasDatabaseName("ix_party_memberships_person_id_start_date");

                    b.ToTable("party_memberships", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Period", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_periods");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_periods_code");

                    b.ToTable("periods", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.RolePeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_role_periods");

                    b.HasIndex("PersonId", "Kind", "StartDate")
                        .HasDatabaseName("ix_role_periods_person_id_kind_start_date");

                    b.ToTable("role_periods", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.SyncState", b =>
                {
                    b.Property<string>("EntityName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("entity_name");

                    b.Property<bool>("FullLoadCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("full_load_completed");

                    b.Property<int?>("LastId")
                        .HasColumnType("integer")
                        .HasColumnName("last_id");

                    b.Property<DateTime?>("LastRunCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_completed_at");

                    b.Property<DateTime?>("LastRunStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_started_at");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<long>("RowsUpserted")
                        .HasColumnType("bigint")
                        .HasColumnName("rows_upserted");

                    b.HasKey("EntityName")
                        .HasName("pk_sync_states");

                    b.ToTable("sync_states", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.Vote", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("CaseStepId")
                        .HasColumnType("integer")
                        .HasColumnName("case_step_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("Conclusion")
                        .HasColumnType("text")
                        .HasColumnName("conclusion");

                    b.Property<int>("MeetingId")
                        .HasColumnType("integer")
                        .HasColumnName("meeting_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_votes");

                    b.HasIndex("CaseStepId")
                        .HasDatabaseName("ix_votes_case_step_id");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("ix_votes_meeting_id");

                    b.ToTable("votes", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.BallotPartyView", b =>
                {
                    b.Property<int>("BallotId")
                        .HasColumnType("integer")
                        .HasColumnName("ballot_id");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<int>("BallotType")
                        .HasColumnType("integer")
                        .HasColumnName("ballot_type");

                    b.Property<string>("PartyShortName")
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<DateTime>("VoteDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("vote_date");

                    b.Property<int>("VoteId")
                        .HasColumnType("integer")
                        .HasColumnName("vote_id");

                    b.Property<bool>("WhileMinister")
                        .HasColumnType("boolean")
                        .HasColumnName("while_minister");

                    b.Property<bool>("WhileOnLeave")
                        .HasColumnType("boolean")
                        .HasColumnName("while_on_leave");

                    b.HasKey("BallotId");

                    b.ToTable((string)null);

                    b.ToView("mv_ballots", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.CurrentMemberView", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("integer")
                        .HasColumnName("person_id");

                    b.Property<string>("PartyShortName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("PersonId");

                    b.ToTable((string)null);

                    b.ToView("mv_current_members", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.PartyStatsView", b =>
                {
                    b.Property<string>("PartyShortName")
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<int>("AgainstMajority")
                        .HasColumnType("integer")
                        .HasColumnName("against_majority");

                    b.Property<int>("Ballots")
                        .HasColumnType("integer")
                        .HasColumnName("ballots");

                    b.Property<int>("Members")
                        .HasColumnType("integer")
                        .HasColumnName("members");

                    b.Property<int>("PresentBallots")
                        .HasColumnType("integer")
                        .HasColumnName("present_ballots");

                    b.Property<int>("WithMajority")
                        .HasColumnType("integer")
                        .HasColumnName("with_majority");

                    b.HasKey("PartyShortName", "PeriodId");

                    b.ToTable((string)null);

                    b.ToView("mv_party_stats", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.PoliticianStatsView", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_id");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<int>("AbsentCount")
                        .HasColumnType("integer")
                        .HasColumnName("absent_count");

                    b.Property<int>("AbstainCount")
                        .HasColumnType("integer")
                        .HasColumnName("abstain_count");

                    b.Property<int>("AgainstCount")
                        .HasColumnType("integer")
                        .HasColumnName("against_count");

                    b.Property<int>("AgainstPartyCount")
                        .HasColumnType("integer")
                        .HasColumnName("against_party_count");

                    b.Property<int>("ForCount")
                        .HasColumnType("integer")
                        .HasColumnName("for_count");

                    b.Property<int>("MinisterAbsent")
                        .HasColumnType("integer")
                        .HasColumnName("minister_absent");

                    b.Property<int>("MinisterTotal")
                        .HasColumnType("integer")
                        .HasColumnName("minister_total");

                    b.Property<int>("RoleAbsent")
                        .HasColumnType("integer")
                        .HasColumnName("role_absent");

                    b.Property<int>("RoleTotal")
                        .HasColumnType("integer")
                        .HasColumnName("role_total");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<int>("WithPartyCount")
                        .HasColumnType("integer")
                        .HasColumnName("with_party_count");

                    b.HasKey("ActorId", "PeriodId");

                    b.ToTable((string)null);

                    b.ToView("mv_politician_stats", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.QuestionView", b =>
                {
                    b.Property<int>("CaseId")
                        .HasColumnType("integer")
                        .HasColumnName("case_id");

                    b.Property<DateTime?>("AnsweredDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("answered_date");

                    b.Property<DateTime?>("AskedDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("asked_date");

                    b.Property<int?>("AskerId")
                        .HasColumnType("integer")
                        .HasColumnName("asker_id");

                    b.Property<string>("AskerParty")
                        .HasColumnType("text")
                        .HasColumnName("asker_party");

                    b.Property<int?>("MinisterPersonId")
                        .HasColumnType("integer")
                        .HasColumnName("minister_person_id");

                    b.Property<string>("MinisterTitle")
                        .HasColumnType("text")
                        .HasColumnName("minister_title");

                    b.Property<string>("Number")
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<bool>("Oral")
                        .HasColumnType("boolean")
                        .HasColumnName("oral");

                    b.Property<int>("PeriodId")
                        .HasColumnType("integer")
                        .HasColumnName("period_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<bool>("Withdrawn")
                        .HasColumnType("boolean")
                        .HasColumnName("withdrawn");

                    b.HasKey("CaseId");

                    b.ToTable((string)null);

                    b.ToView("mv_questions", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.TopicStatsView", b =>
                {
                    b.Property<int>("KeywordId")
                        .HasColumnType("integer")
                        .HasColumnName("keyword_id");

                    b.Property<int>("CaseCount")
                        .HasColumnType("integer")
                        .HasColumnName("case_count");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer")
                        .HasColumnName("vote_count");

                    b.HasKey("KeywordId");

                    b.ToTable((string)null);

                    b.ToView("mv_topic_stats", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.VotePartyBreakdownView", b =>
                {
                    b.Property<int>("AbsentCount")
                        .HasColumnType("integer")
                        .HasColumnName("absent_count");

                    b.Property<int>("AbstainCount")
                        .HasColumnType("integer")
                        .HasColumnName("abstain_count");

                    b.Property<int>("AgainstCount")
                        .HasColumnType("integer")
                        .HasColumnName("against_count");

                    b.Property<int>("ForCount")
                        .HasColumnType("integer")
                        .HasColumnName("for_count");

                    b.Property<int?>("MajorityBallotType")
                        .HasColumnType("integer")
                        .HasColumnName("majority_ballot_type");

                    b.Property<string>("PartyShortName")
                        .HasColumnType("text")
                        .HasColumnName("party_short_name");

                    b.Property<int>("VoteId")
                        .HasColumnType("integer")
                        .HasColumnName("vote_id");

                    b.ToTable((string)null);

                    b.ToView("mv_vote_party_breakdown", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Data.Persistence.Views.VoteTotalsView", b =>
                {
                    b.Property<int>("VoteId")
                        .HasColumnType("integer")
                        .HasColumnName("vote_id");

                    b.Property<int>("AbsentCount")
                        .HasColumnType("integer")
                        .HasColumnName("absent_count");

                    b.Property<int>("AbstainCount")
                        .HasColumnType("integer")
                        .HasColumnName("abstain_count");

                    b.Property<int>("AgainstCount")
                        .HasColumnType("integer")
                        .HasColumnName("against_count");

                    b.Property<int>("ForCount")
                        .HasColumnType("integer")
                        .HasColumnName("for_count");

                    b.HasKey("VoteId");

                    b.ToTable((string)null);

                    b.ToView("mv_vote_totals", (string)null);
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.PartyDonation", b =>
                {
                    b.HasOne("FolketingetVotes.Core.Entities.PartyAccount", "PartyAccount")
                        .WithMany("Donations")
                        .HasForeignKey("PartyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_donations_party_accounts_party_account_id");

                    b.Navigation("PartyAccount");
                });

            modelBuilder.Entity("FolketingetVotes.Core.Entities.PartyAccount", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
